name: Package CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -f @ull-esit-pl-1920/p10-t2-lexgen-code-alu0101100654@0.2.3
      - run: npm jest
      - run: npm ci
      - run: npm test
        env:
            CI: true
